[package]

name = "omwot/images"
description = "Image asset management library"
version = "1.0.0"
realm = "shared"

authors = ["omwot"]
license = "MIT"

registry = "https://github.com/UpliftGames/wally-index"

# These are not essential
exclude = ["Assets"]

[dependencies]
