-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Assets = {
		Qt = {
			icons = {
				Light = {
					Roblox = {
						["16"] = {
							["3x"] = {
								ACCodeSnippet = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACEnum = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACEvent = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACFunction = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACKeyword = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACProperty = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACText = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								ACVariable = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Accessory = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								AccessoryFittingTool = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Actor = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								AdGui = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(0, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								AdPortal = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								Add = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								AddNoBorder = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								AddWatch = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								AirController = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								AlignOrientation = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								AlignPosition = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								AlignTool = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Anchor = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								AngularVelocity = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Animation = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								AnimationConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 343),
									ImageRectSize = Vector2.new(48, 45),
								},
								AnimationController = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								AnimationEditor = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								AnimationFromVideoCreatorService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Animator = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								ArcHandles = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(0, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								ArrowDown = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								ArrowRight = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								AssetManager = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								Atmosphere = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Attachment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioAnalyzer = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioChorus = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioCompressor = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioDeviceInput = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioDeviceOutput = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioDistortion = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioEcho = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioEmitter = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioEqualizer = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioFader = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioFlanger = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioListener = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(0, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioPitchShifter = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioPlayer = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								AudioReverb = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								AutoWeight = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								AutoupdateOn = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								AvatarEditorService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								AvatarImporter = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								Back = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Backpack = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								BallSocket = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								BallSocketConstraint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								BasePlate = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Beam = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								BillboardGui = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								BindableEvent = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								BindableFunction = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								BlockMesh = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								BloomEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(0, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								BlurEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyAngularVelocity = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyColors = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyForce = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyGyro = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyPosition = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyThrust = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								BodyVelocity = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Bold_Default = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Bold_Selected = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Bone = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								BoolValue = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								BoundingBox = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								BoxHandleAdornment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Breakpoint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Breakpoints = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								BrickColorValue = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								BubbleChatConfiguration = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Buggaroo = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(0, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								CFrameValue = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								CageMode = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								CageVisibility = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								CallStack = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Camera = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								CameraToMannequin = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								CanvasGroup = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								CharacterControllerManager = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								CharacterMesh = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Chat = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								ChatInputBarConfiguration = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								ChatWindowConfiguration = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								ChorusSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Class = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Cleanup = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClearInput = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClearStats = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClickDetector = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Client = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClientReplicator = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(0, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClientRunContext = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClimbController = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								CloseWidget = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								ClosedHandPointer = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Clouds = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Collapse = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								CollisionGroups = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Color = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								ColorCorrectionEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								ColorPicker = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								CommandBar = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								CompressorSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConditionalBreakpoint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConditionalBreakpointDisabled = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConeHandleAdornment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Configuration = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConnectionFailed = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConnectionStable = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConnectionUnstable = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(49, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Constant = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								ConstraintDetails = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Constructor = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Copy = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								CoreGui = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								CornerWedgePart = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								CreateConstraints = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Cut = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								CylinderHandleAdornment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Cylindrical = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								CylindricalConstraint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Decal = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Delete = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								DeleteAllBreakpoints = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								DeleteSelectedBreakpoints = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								DepthOfFieldEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Device = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								DeviceSafeArea = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(98, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Dialog = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								DialogChoice = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								DisableAllBreakpoints = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								DistortionSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								Download = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Draft = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								DragDetector = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								DrawOnTop = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								DropdownArrow = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Duplicate = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								EchoSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								EditPivot = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Effects = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Enum = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								EnumMember = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								EqualizerSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								Error = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(147, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Event = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								ExitGame = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Expand = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								ExpandAll = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Explorer = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								ExplorerSelectAll = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								ExplorerSelectAllOld = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 392),
									ImageRectSize = Vector2.new(48, 45),
								},
								Explosion = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								FaceControls = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Favorited = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								FavoritesTab_Default = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 441),
									ImageRectSize = Vector2.new(48, 45),
								},
								FavoritesTab_Selected = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 490),
									ImageRectSize = Vector2.new(48, 45),
								},
								Field = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								File = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Filter = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								FilterWithDropdown = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Find = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								FindAll = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								FindNext = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(196, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								FindPrevious = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Fire = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								FlangeSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Folder = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								ForceField = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								FormatDocument = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								FormatSelection = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Frame = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								FullScreen = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Function = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Fwd = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Gallery = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								GameSettings = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								GlobalWindControl = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(882, 98),
									ImageRectSize = Vector2.new(48, 47),
								},
								GoToLine = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								GridMaterial = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(245, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								GroundController = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								Group = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Handles = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								HapticService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								HeightmapImporterService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Highlight = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Hinge = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								HingeConstraint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								HorizontalDoubleArrow = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Hover = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Humanoid = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								HumanoidDescription = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								IKControl = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								ImageButton = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(294, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								ImageHandleAdornment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								ImageLabel = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								InnerCage = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								InsertObject = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Interface = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								IntersectOperation = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								InvalidBreakpoint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								InvalidLogpoint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								InventoryTab_Default = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(0, 56),
									ImageRectSize = Vector2.new(48, 55),
								},
								InventoryTab_Selected = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(98, 0),
									ImageRectSize = Vector2.new(48, 55),
								},
								Italic_Default = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Italic_Selected = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Keyword = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								LegacyClientRunContext = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								LegacyServerRunContext = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(343, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Lighting = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								LineForce = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								LineHandleAdornment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								LinearVelocity = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								LocalFile = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								LocalScript = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								LocalizationService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								LocalizationTable = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Lock = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								LockAll = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								LockCursor = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								LockTool = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(392, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Logpoint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								LogpointDisabled = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								ManagePlugins = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								MarketplaceIcon = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								MarketplaceIcon_Default = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								MarketplaceIcon_Selected = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								MatchCase = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								MatchWholeWord = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Material = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								MaterialService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								MaterialVariant = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(441, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								MemoryStoreService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								MeshPart = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								MeshVisibility = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Meshparts = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								MessagingService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Method = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Model = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Modelgroups = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Modified = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								ModifiedPackage = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(490, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Module = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								ModuleScript = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								More = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Motor6D = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Move = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Move_P = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Mute = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								NegateOperation = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								NetworkClient = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(539, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								NewFile = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								NextResult = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								NoCollision = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								NoCollisionConstraint = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								NotFavorited = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 539),
									ImageRectSize = Vector2.new(48, 45),
								},
								NotificationBell = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								NotificationBellNew = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								ObjectBrowser = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								Open = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(588, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								OpenHandPointer = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								OpenScriptFunctionFilter = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Operator = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								OptionsDots = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								OuterCage = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Outline = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								OutlineBoundingBox = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(637, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Output = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								Package = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								PackageLink = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								PackageLinkAttatchment = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Packages = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								PanCamera = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(686, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Pants = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								Part = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Part_Block = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Part_CornerWedge = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								Part_Cylinder = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(735, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Part_Sphere = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Part_Wedge = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								ParticleEmitter = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								Paste = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(784, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								PathfindingLink = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								PathfindingModifier = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								PathfindingService = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(833, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Pause = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								Performance = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(882, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								PitchShiftSoundEffect = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(931, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
								Place = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								PlaceCloud = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								PlaceLocal = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								Placeholder = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								Plane = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								PlaneConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								Play = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								PlayHere = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								Player = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								Players = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								PluginGuiService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								PluginRunContext = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								PluginsFolder = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								PointLight = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Pointer = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								PreviousResult = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								PreviousResultOld = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								Prismatic = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								PrismaticConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Properties = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Property = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								ProximityPrompt = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								PublishService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								QuickOpen = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								QuickOpenActions = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Redo = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Reference = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Refresh = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								RefreshOld = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								RegularExpression = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								RemoteEvent = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								RemoteFunction = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								RenderingTest = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Replace = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								ReplicatedFirst = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								ReplicatedScriptService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								ReplicatedStorage = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								ResetPivot = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								ResizeDiagonal = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								ResizeHorizontal = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								ResizeVertical = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Resume = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								ReverbSoundEffect = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								Rigid = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								RigidConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								RobloxPluginGuiService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								RocketPropulsion = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								Rod = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								RodConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								RopeConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Rotate = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Rotate_P = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								Run = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								RunScript = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Save = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Scale = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								Scale_P = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScreenGui = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScreenShot = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Script = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScriptAnalysis = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScriptPerformance = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScriptRecovery = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScrollbarDown = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScrollbarTriangle = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(0, 994),
									ImageRectSize = Vector2.new(48, 27),
								},
								ScrollbarUp = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								ScrollingFrame = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Seat = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								Select = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								SelectAll = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								SelectChildren = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								SelectText = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Select_P = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Selected_Workspace = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								SelectionBox = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								SelectionSphere = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Separate = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Server = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								ServerRunContext = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								ServerScriptService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								ServerStorage = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								Service = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								Settings = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Shirt = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								ShirtGraphic = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								ShowGrid = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								ShowWelds = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								SkinnedMeshPart = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Sky = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Smoke = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Snap = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Snippet = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								SocialService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								Sound = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								SoundEffect = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								SoundGroup = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								SoundService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Sparkles = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								SpawnLocation = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								SpecialMesh = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								SphereHandleAdornment = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								SpotLight = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Spring = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								SpringConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								StandalonePluginScripts = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								StartServerAndClient = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								StarterCharacterScripts = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								StarterGui = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								StarterPack = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								StarterPlayer = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								StarterPlayerScripts = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								StepInto = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								StepOut = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								StepOver = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Stop = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Strikethrough_Default = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Strikethrough_Selected = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								Struct = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								SunRaysEffect = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								SurfaceAppearance = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								SurfaceGui = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								SurfaceLight = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(735, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								SurfaceSelection = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								SwimController = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								SwitchWindows = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								TagEditor = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								TaskScheduler = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Team = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								TeamCreate = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								TeamTest = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Teams = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Terrain = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								TerrainDetail = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								TerrainEditor = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								TestService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextBox = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextBoxService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextButton = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(784, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextChannel = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(735, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextChatCommand = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextChatService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextLabel = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								TextString = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Texture = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								Tool = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Toolbox = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								Torque = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								TorsionSpring = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								TorsionSpringConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Trail = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Transform = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								Transparency = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								TremoloSoundEffect = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								TrussPart = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								TypeParameter = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(833, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								UGCValidationService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(784, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								UI = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(735, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIAspectRatioConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								UICorner = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIGradient = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIGridLayout = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIListLayout = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIOff = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIOn = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIPadding = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIPageLayout = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIScale = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								UISizeConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								UIStroke = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								UITableLayout = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								UITextSizeConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								Underline_Default = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								Underline_Selected = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(882, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								Undo = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(833, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								UndockPreviewWindow = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(784, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								Ungroup = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(735, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								UnionOperation = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Unit = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Universal = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								UniversalConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Unlock = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								UnlockCursor = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								UpdateAvailable = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								UserService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								Value = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Variable = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								VectorForce = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								VehicleSeat = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								VideoFrame = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								VideoRecord = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								ViewSelector = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								ViewportFrame = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(931, 0),
									ImageRectSize = Vector2.new(48, 48),
								},
								VirtualUser = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(882, 49),
									ImageRectSize = Vector2.new(48, 48),
								},
								VoiceChannel = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(833, 98),
									ImageRectSize = Vector2.new(48, 48),
								},
								VoiceChatService = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(784, 147),
									ImageRectSize = Vector2.new(48, 48),
								},
								Voicechat = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(735, 196),
									ImageRectSize = Vector2.new(48, 48),
								},
								Warning = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 245),
									ImageRectSize = Vector2.new(48, 48),
								},
								Watch = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(637, 294),
									ImageRectSize = Vector2.new(48, 48),
								},
								WedgePart = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 343),
									ImageRectSize = Vector2.new(48, 48),
								},
								Weld = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(539, 392),
									ImageRectSize = Vector2.new(48, 48),
								},
								WeldConstraint = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 441),
									ImageRectSize = Vector2.new(48, 48),
								},
								Wire = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(441, 490),
									ImageRectSize = Vector2.new(48, 48),
								},
								WireframeHandleAdornment = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(392, 539),
									ImageRectSize = Vector2.new(48, 48),
								},
								WireframeRendering = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 588),
									ImageRectSize = Vector2.new(48, 48),
								},
								Workspace = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(294, 637),
									ImageRectSize = Vector2.new(48, 48),
								},
								WorldModel = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 686),
									ImageRectSize = Vector2.new(48, 48),
								},
								WrapLayer = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(196, 735),
									ImageRectSize = Vector2.new(48, 48),
								},
								WrapTarget = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 784),
									ImageRectSize = Vector2.new(48, 48),
								},
								ZoomIn = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(98, 833),
									ImageRectSize = Vector2.new(48, 48),
								},
								ZoomOut = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 882),
									ImageRectSize = Vector2.new(48, 48),
								},
								ZoomTo = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(0, 931),
									ImageRectSize = Vector2.new(48, 48),
								},
							},
						},
					},
				},
			},
		},
	},
}