-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Assets = {
		Qt = {
			icons = {
				Light = {
					Roblox = {
						["16"] = {
							["2x"] = {
								ACCodeSnippet = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACEnum = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACKeyword = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACProperty = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACText = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								ACVariable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								Accessory = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								AccessoryFittingTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Actor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								AdGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								AdPortal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Add = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								AddNoBorder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								AddWatch = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								AirController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								AlignOrientation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								AlignPosition = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								AlignTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Anchor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								AngularVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Animation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								AnimationConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 528),
									ImageRectSize = Vector2.new(32, 30),
								},
								AnimationController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								AnimationEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								AnimationFromVideoCreatorService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Animator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								ArcHandles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								ArrowDown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								ArrowRight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								AssetManager = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								Atmosphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								Attachment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioAnalyzer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioChorus = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioCompressor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioDeviceInput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioDeviceOutput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioDistortion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioEcho = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioEmitter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioEqualizer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioFader = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioFlanger = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioListener = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioPitchShifter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioPlayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								AudioReverb = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								AutoWeight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								AutoupdateOn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								AvatarEditorService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								AvatarImporter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Back = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Backpack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								BallSocket = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								BallSocketConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								BasePlate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								Beam = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								BillboardGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								BindableEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								BindableFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								BlockMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								BloomEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								BlurEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyAngularVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyColors = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyGyro = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyPosition = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyThrust = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								BodyVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Bold_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								Bold_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Bone = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								BoolValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								BoundingBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								BoxHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								Breakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								Breakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								BrickColorValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								BubbleChatConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								Buggaroo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								CFrameValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								CageMode = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								CageVisibility = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								CallStack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								Camera = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								CameraToMannequin = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								CanvasGroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								CharacterControllerManager = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								CharacterMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								Chat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								ChatInputBarConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								ChatWindowConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								ChorusSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								Class = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								Cleanup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClearInput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClearStats = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClickDetector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Client = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClientReplicator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClientRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClimbController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								CloseWidget = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								ClosedHandPointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								Clouds = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Collapse = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								CollisionGroups = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Color = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								ColorCorrectionEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								ColorPicker = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								CommandBar = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								CompressorSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConditionalBreakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConditionalBreakpointDisabled = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConeHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Configuration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConnectionFailed = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConnectionStable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConnectionUnstable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Constant = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								ConstraintDetails = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								Constructor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Copy = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								CoreGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								CornerWedgePart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								CreateConstraints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Cut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								CylinderHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Cylindrical = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								CylindricalConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								Decal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Delete = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								DeleteAllBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								DeleteSelectedBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								DepthOfFieldEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								Device = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								DeviceSafeArea = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								Dialog = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								DialogChoice = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								DisableAllBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								DistortionSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Download = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								Draft = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								DragDetector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								DrawOnTop = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								DropdownArrow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								Duplicate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								EchoSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								EditPivot = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								Effects = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Enum = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								EnumMember = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								EqualizerSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Error = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								Event = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								ExitGame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								Expand = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								ExpandAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Explorer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								ExplorerSelectAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								ExplorerSelectAllOld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 561),
									ImageRectSize = Vector2.new(32, 30),
								},
								Explosion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								FaceControls = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								Favorited = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								FavoritesTab_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 594),
									ImageRectSize = Vector2.new(32, 30),
								},
								FavoritesTab_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 627),
									ImageRectSize = Vector2.new(32, 30),
								},
								Field = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								File = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								Filter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								FilterWithDropdown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Find = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								FindAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								FindNext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								FindPrevious = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Fire = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								FlangeSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Folder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								ForceField = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								FormatDocument = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								FormatSelection = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								Frame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								FullScreen = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								Function = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								Fwd = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Gallery = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								GameSettings = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								GlobalWindControl = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 363),
									ImageRectSize = Vector2.new(32, 31),
								},
								GoToLine = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								GridMaterial = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								GroundController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								Group = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								Handles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								HapticService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								HeightmapImporterService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								Highlight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Hinge = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								HingeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								HorizontalDoubleArrow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								Hover = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Humanoid = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								HumanoidDescription = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								IKControl = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								ImageButton = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								ImageHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								ImageLabel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								InnerCage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								InsertObject = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								Interface = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								IntersectOperation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								InvalidBreakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								InvalidLogpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								InventoryTab_Default = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 98),
									ImageRectSize = Vector2.new(32, 37),
								},
								InventoryTab_Selected = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 147),
									ImageRectSize = Vector2.new(32, 37),
								},
								Italic_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								Italic_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Keyword = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								LegacyClientRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								LegacyServerRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								Lighting = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								LineForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								LineHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								LinearVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								LocalFile = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								LocalScript = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								LocalizationService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								LocalizationTable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Lock = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								LockAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								LockCursor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								LockTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								Logpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								LogpointDisabled = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								ManagePlugins = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								MarketplaceIcon = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								MarketplaceIcon_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								MarketplaceIcon_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								MatchCase = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								MatchWholeWord = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								Material = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								MaterialService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								MaterialVariant = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								MemoryStoreService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								MeshPart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								MeshVisibility = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								Meshparts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								MessagingService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								Method = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								Model = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Modelgroups = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								Modified = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								ModifiedPackage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								Module = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								ModuleScript = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								More = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Motor6D = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Move = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								Move_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Mute = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								NegateOperation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								NetworkClient = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								NewFile = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								NextResult = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								NoCollision = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								NoCollisionConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								NotFavorited = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 660),
									ImageRectSize = Vector2.new(32, 30),
								},
								NotificationBell = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								NotificationBellNew = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								ObjectBrowser = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Open = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								OpenHandPointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								OpenScriptFunctionFilter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								Operator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								OptionsDots = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								OuterCage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								Outline = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								OutlineBoundingBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Output = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								Package = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								PackageLink = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								PackageLinkAttatchment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Packages = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								PanCamera = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Pants = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Part = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								Part_Block = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Part_CornerWedge = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								Part_Cylinder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								Part_Sphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								Part_Wedge = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								ParticleEmitter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Paste = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								PathfindingLink = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								PathfindingModifier = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								PathfindingService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Pause = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Performance = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								PitchShiftSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								Place = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								PlaceCloud = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								PlaceLocal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								Placeholder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Plane = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								PlaneConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								Play = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								PlayHere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								Player = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								Players = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								PluginGuiService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								PluginRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								PluginsFolder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								PointLight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Pointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								PreviousResult = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								PreviousResultOld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								Prismatic = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								PrismaticConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								Properties = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								Property = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								ProximityPrompt = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								PublishService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								QuickOpen = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								QuickOpenActions = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Redo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Reference = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								Refresh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								RefreshOld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								RegularExpression = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								RemoteEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								RemoteFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								RenderingTest = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								Replace = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								ReplicatedFirst = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								ReplicatedScriptService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								ReplicatedStorage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								ResetPivot = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								ResizeDiagonal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								ResizeHorizontal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								ResizeVertical = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								Resume = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								ReverbSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								Rigid = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								RigidConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								RobloxPluginGuiService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								RocketPropulsion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								Rod = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								RodConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								RopeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Rotate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								Rotate_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								Run = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								RunScript = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Save = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Scale = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								Scale_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScreenGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScreenShot = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								Script = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 957),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScriptAnalysis = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 0),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScriptPerformance = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScriptRecovery = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScrollbarDown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScrollbarTriangle = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 997),
									ImageRectSize = Vector2.new(32, 18),
								},
								ScrollbarUp = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								ScrollingFrame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Seat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								Select = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								SelectAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								SelectChildren = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								SelectText = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								Select_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								Selected_Workspace = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								SelectionBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								SelectionSphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								Separate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								Server = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								ServerRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								ServerScriptService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								ServerStorage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Service = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								Settings = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								Shirt = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								ShirtGraphic = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								ShowGrid = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								ShowWelds = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								SkinnedMeshPart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								Sky = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								Smoke = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								Snap = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 957),
									ImageRectSize = Vector2.new(32, 32),
								},
								Snippet = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(0, 990),
									ImageRectSize = Vector2.new(32, 32),
								},
								SocialService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 33),
									ImageRectSize = Vector2.new(32, 32),
								},
								Sound = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								SoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								SoundGroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								SoundService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								Sparkles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								SpawnLocation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								SpecialMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								SphereHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								SpotLight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								Spring = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								SpringConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								StandalonePluginScripts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								StartServerAndClient = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								StarterCharacterScripts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								StarterGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								StarterPack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								StarterPlayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								StarterPlayerScripts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								StepInto = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								StepOut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								StepOver = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								Stop = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Strikethrough_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Strikethrough_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								Struct = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								SunRaysEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								SurfaceAppearance = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								SurfaceGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 957),
									ImageRectSize = Vector2.new(32, 32),
								},
								SurfaceLight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(33, 990),
									ImageRectSize = Vector2.new(32, 32),
								},
								SurfaceSelection = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 66),
									ImageRectSize = Vector2.new(32, 32),
								},
								SwimController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								SwitchWindows = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								TagEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								TaskScheduler = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								Team = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								TeamCreate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								TeamTest = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Teams = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								Terrain = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								TerrainDetail = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								TerrainEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								TestService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextBoxService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextButton = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextChannel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextChatCommand = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextChatService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextLabel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								TextString = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								Texture = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Tool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Toolbox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								Torque = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								TorsionSpring = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								TorsionSpringConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								Trail = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 957),
									ImageRectSize = Vector2.new(32, 32),
								},
								Transform = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(66, 990),
									ImageRectSize = Vector2.new(32, 32),
								},
								Transparency = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 99),
									ImageRectSize = Vector2.new(32, 32),
								},
								TremoloSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								TrussPart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								TypeParameter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								UGCValidationService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								UI = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIAspectRatioConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								UICorner = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIGradient = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIGridLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIListLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIOff = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIOn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIPadding = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIPageLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIScale = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								UISizeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								UIStroke = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								UITableLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								UITextSizeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								Underline_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Underline_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								Undo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								UndockPreviewWindow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								Ungroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								UnionOperation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								Unit = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 957),
									ImageRectSize = Vector2.new(32, 32),
								},
								Universal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(99, 990),
									ImageRectSize = Vector2.new(32, 32),
								},
								UniversalConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 132),
									ImageRectSize = Vector2.new(32, 32),
								},
								Unlock = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								UnlockCursor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								UpdateAvailable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								UserService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								Value = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
								Variable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 330),
									ImageRectSize = Vector2.new(32, 32),
								},
								VectorForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 363),
									ImageRectSize = Vector2.new(32, 32),
								},
								VehicleSeat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 396),
									ImageRectSize = Vector2.new(32, 32),
								},
								VideoFrame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 429),
									ImageRectSize = Vector2.new(32, 32),
								},
								VideoRecord = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 462),
									ImageRectSize = Vector2.new(32, 32),
								},
								ViewSelector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 495),
									ImageRectSize = Vector2.new(32, 32),
								},
								ViewportFrame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 528),
									ImageRectSize = Vector2.new(32, 32),
								},
								VirtualUser = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 561),
									ImageRectSize = Vector2.new(32, 32),
								},
								VoiceChannel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 594),
									ImageRectSize = Vector2.new(32, 32),
								},
								VoiceChatService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 627),
									ImageRectSize = Vector2.new(32, 32),
								},
								Voicechat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 660),
									ImageRectSize = Vector2.new(32, 32),
								},
								Warning = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 693),
									ImageRectSize = Vector2.new(32, 32),
								},
								Watch = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 726),
									ImageRectSize = Vector2.new(32, 32),
								},
								WedgePart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 759),
									ImageRectSize = Vector2.new(32, 32),
								},
								Weld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 792),
									ImageRectSize = Vector2.new(32, 32),
								},
								WeldConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 825),
									ImageRectSize = Vector2.new(32, 32),
								},
								Wire = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 858),
									ImageRectSize = Vector2.new(32, 32),
								},
								WireframeHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 891),
									ImageRectSize = Vector2.new(32, 32),
								},
								WireframeRendering = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 924),
									ImageRectSize = Vector2.new(32, 32),
								},
								Workspace = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 957),
									ImageRectSize = Vector2.new(32, 32),
								},
								WorldModel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(132, 990),
									ImageRectSize = Vector2.new(32, 32),
								},
								WrapLayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 165),
									ImageRectSize = Vector2.new(32, 32),
								},
								WrapTarget = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 198),
									ImageRectSize = Vector2.new(32, 32),
								},
								ZoomIn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 231),
									ImageRectSize = Vector2.new(32, 32),
								},
								ZoomOut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 264),
									ImageRectSize = Vector2.new(32, 32),
								},
								ZoomTo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 297),
									ImageRectSize = Vector2.new(32, 32),
								},
							},
						},
					},
				},
			},
		},
	},
}