-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Assets = {
		Qt = {
			icons = {
				Dark = {
					Roblox = {
						["16"] = {
							["1x"] = {
								ACCodeSnippet = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(245, 999),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACEnum = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(343, 1000),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACEvent = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(490, 998),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACFunction = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(588, 999),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACKeyword = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(686, 1000),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACProperty = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(784, 1001),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACText = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(882, 1004),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACVariable = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(980, 1006),
									ImageRectSize = Vector2.new(16, 16),
								},
								Accessory = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(66, 997),
									ImageRectSize = Vector2.new(16, 16),
								},
								AccessoryFittingTool = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(164, 998),
									ImageRectSize = Vector2.new(16, 16),
								},
								Actor = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(262, 999),
									ImageRectSize = Vector2.new(16, 16),
								},
								AdGui = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(360, 1000),
									ImageRectSize = Vector2.new(16, 16),
								},
								AdPortal = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(507, 998),
									ImageRectSize = Vector2.new(16, 16),
								},
								Add = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(605, 999),
									ImageRectSize = Vector2.new(16, 16),
								},
								AddNoBorder = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(703, 1000),
									ImageRectSize = Vector2.new(16, 16),
								},
								AddWatch = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(801, 1001),
									ImageRectSize = Vector2.new(16, 16),
								},
								AirController = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(899, 1004),
									ImageRectSize = Vector2.new(16, 16),
								},
								AlignOrientation = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(997, 1006),
									ImageRectSize = Vector2.new(16, 16),
								},
								AlignPosition = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 693),
									ImageRectSize = Vector2.new(16, 16),
								},
								AlignTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 726),
									ImageRectSize = Vector2.new(16, 16),
								},
								Anchor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 759),
									ImageRectSize = Vector2.new(16, 16),
								},
								AngularVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 792),
									ImageRectSize = Vector2.new(16, 16),
								},
								Animation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 825),
									ImageRectSize = Vector2.new(16, 16),
								},
								AnimationConstraint = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 229),
									ImageRectSize = Vector2.new(16, 15),
								},
								AnimationController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 858),
									ImageRectSize = Vector2.new(16, 16),
								},
								AnimationEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 891),
									ImageRectSize = Vector2.new(16, 16),
								},
								AnimationFromVideoCreatorService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 924),
									ImageRectSize = Vector2.new(16, 16),
								},
								Animator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 957),
									ImageRectSize = Vector2.new(16, 16),
								},
								ArcHandles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(165, 990),
									ImageRectSize = Vector2.new(16, 16),
								},
								ArrowDown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 198),
									ImageRectSize = Vector2.new(16, 16),
								},
								ArrowRight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 231),
									ImageRectSize = Vector2.new(16, 16),
								},
								AssetManager = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 264),
									ImageRectSize = Vector2.new(16, 16),
								},
								Atmosphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 297),
									ImageRectSize = Vector2.new(16, 16),
								},
								Attachment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 330),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioAnalyzer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 362),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioChorus = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 395),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioCompressor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 427),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioDeviceInput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 460),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioDeviceOutput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 493),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioDistortion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 526),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioEcho = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 559),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioEmitter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 592),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioEqualizer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 625),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioFader = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 658),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioFlanger = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 691),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioListener = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 710),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioPitchShifter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 743),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioPlayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 776),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioReverb = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 809),
									ImageRectSize = Vector2.new(16, 16),
								},
								AutoWeight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 842),
									ImageRectSize = Vector2.new(16, 16),
								},
								AutoupdateOn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 875),
									ImageRectSize = Vector2.new(16, 16),
								},
								AvatarEditorService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 908),
									ImageRectSize = Vector2.new(16, 16),
								},
								AvatarImporter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 941),
									ImageRectSize = Vector2.new(16, 16),
								},
								Back = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 974),
									ImageRectSize = Vector2.new(16, 16),
								},
								Backpack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 215),
									ImageRectSize = Vector2.new(16, 16),
								},
								BallSocket = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 248),
									ImageRectSize = Vector2.new(16, 16),
								},
								BallSocketConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 281),
									ImageRectSize = Vector2.new(16, 16),
								},
								BasePlate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 314),
									ImageRectSize = Vector2.new(16, 16),
								},
								Beam = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 347),
									ImageRectSize = Vector2.new(16, 16),
								},
								BillboardGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 379),
									ImageRectSize = Vector2.new(16, 16),
								},
								BindableEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 412),
									ImageRectSize = Vector2.new(16, 16),
								},
								BindableFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 444),
									ImageRectSize = Vector2.new(16, 16),
								},
								BlockMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 477),
									ImageRectSize = Vector2.new(16, 16),
								},
								BloomEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 510),
									ImageRectSize = Vector2.new(16, 16),
								},
								BlurEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 543),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyAngularVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 576),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyColors = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 609),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 642),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyGyro = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 675),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyPosition = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 708),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyThrust = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 727),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 760),
									ImageRectSize = Vector2.new(16, 16),
								},
								Bold_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 793),
									ImageRectSize = Vector2.new(16, 16),
								},
								Bold_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 826),
									ImageRectSize = Vector2.new(16, 16),
								},
								Bone = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 859),
									ImageRectSize = Vector2.new(16, 16),
								},
								BoolValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 892),
									ImageRectSize = Vector2.new(16, 16),
								},
								BoundingBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 925),
									ImageRectSize = Vector2.new(16, 16),
								},
								BoxHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 958),
									ImageRectSize = Vector2.new(16, 16),
								},
								Breakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(198, 991),
									ImageRectSize = Vector2.new(16, 16),
								},
								Breakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 232),
									ImageRectSize = Vector2.new(16, 16),
								},
								BrickColorValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 265),
									ImageRectSize = Vector2.new(16, 16),
								},
								BubbleChatConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 298),
									ImageRectSize = Vector2.new(16, 16),
								},
								Buggaroo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 331),
									ImageRectSize = Vector2.new(16, 16),
								},
								CFrameValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 364),
									ImageRectSize = Vector2.new(16, 16),
								},
								CageMode = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 396),
									ImageRectSize = Vector2.new(16, 16),
								},
								CageVisibility = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 429),
									ImageRectSize = Vector2.new(16, 16),
								},
								CallStack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 461),
									ImageRectSize = Vector2.new(16, 16),
								},
								Camera = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 494),
									ImageRectSize = Vector2.new(16, 16),
								},
								CameraToMannequin = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 527),
									ImageRectSize = Vector2.new(16, 16),
								},
								CanvasGroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 560),
									ImageRectSize = Vector2.new(16, 16),
								},
								CharacterControllerManager = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 593),
									ImageRectSize = Vector2.new(16, 16),
								},
								CharacterMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 626),
									ImageRectSize = Vector2.new(16, 16),
								},
								Chat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 659),
									ImageRectSize = Vector2.new(16, 16),
								},
								ChatInputBarConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 692),
									ImageRectSize = Vector2.new(16, 16),
								},
								ChatWindowConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 725),
									ImageRectSize = Vector2.new(16, 16),
								},
								ChorusSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 744),
									ImageRectSize = Vector2.new(16, 16),
								},
								Class = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 777),
									ImageRectSize = Vector2.new(16, 16),
								},
								Cleanup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 810),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClearInput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 843),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClearStats = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 876),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClickDetector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 909),
									ImageRectSize = Vector2.new(16, 16),
								},
								Client = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 942),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClientReplicator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 975),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClientRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 249),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClimbController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 282),
									ImageRectSize = Vector2.new(16, 16),
								},
								CloseWidget = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 315),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClosedHandPointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 348),
									ImageRectSize = Vector2.new(16, 16),
								},
								Clouds = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 381),
									ImageRectSize = Vector2.new(16, 16),
								},
								Collapse = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 413),
									ImageRectSize = Vector2.new(16, 16),
								},
								CollisionGroups = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 446),
									ImageRectSize = Vector2.new(16, 16),
								},
								Color = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 478),
									ImageRectSize = Vector2.new(16, 16),
								},
								ColorCorrectionEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 511),
									ImageRectSize = Vector2.new(16, 16),
								},
								ColorPicker = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 544),
									ImageRectSize = Vector2.new(16, 16),
								},
								CommandBar = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 577),
									ImageRectSize = Vector2.new(16, 16),
								},
								CompressorSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 610),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConditionalBreakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 643),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConditionalBreakpointDisabled = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 676),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConeHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 709),
									ImageRectSize = Vector2.new(16, 16),
								},
								Configuration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 742),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConnectionFailed = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 761),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConnectionStable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 794),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConnectionUnstable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 827),
									ImageRectSize = Vector2.new(16, 16),
								},
								Constant = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 860),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConstraintDetails = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 893),
									ImageRectSize = Vector2.new(16, 16),
								},
								Constructor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 926),
									ImageRectSize = Vector2.new(16, 16),
								},
								Copy = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 959),
									ImageRectSize = Vector2.new(16, 16),
								},
								CoreGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(231, 992),
									ImageRectSize = Vector2.new(16, 16),
								},
								CornerWedgePart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 266),
									ImageRectSize = Vector2.new(16, 16),
								},
								CreateConstraints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 299),
									ImageRectSize = Vector2.new(16, 16),
								},
								Cut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 332),
									ImageRectSize = Vector2.new(16, 16),
								},
								CylinderHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 365),
									ImageRectSize = Vector2.new(16, 16),
								},
								Cylindrical = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 398),
									ImageRectSize = Vector2.new(16, 16),
								},
								CylindricalConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 430),
									ImageRectSize = Vector2.new(16, 16),
								},
								Decal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 463),
									ImageRectSize = Vector2.new(16, 16),
								},
								Delete = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 495),
									ImageRectSize = Vector2.new(16, 16),
								},
								DeleteAllBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 528),
									ImageRectSize = Vector2.new(16, 16),
								},
								DeleteSelectedBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 561),
									ImageRectSize = Vector2.new(16, 16),
								},
								DepthOfFieldEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 594),
									ImageRectSize = Vector2.new(16, 16),
								},
								Device = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 627),
									ImageRectSize = Vector2.new(16, 16),
								},
								DeviceSafeArea = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 660),
									ImageRectSize = Vector2.new(16, 16),
								},
								Dialog = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 693),
									ImageRectSize = Vector2.new(16, 16),
								},
								DialogChoice = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 726),
									ImageRectSize = Vector2.new(16, 16),
								},
								DisableAllBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 759),
									ImageRectSize = Vector2.new(16, 16),
								},
								DistortionSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 778),
									ImageRectSize = Vector2.new(16, 16),
								},
								Download = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 811),
									ImageRectSize = Vector2.new(16, 16),
								},
								Draft = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 844),
									ImageRectSize = Vector2.new(16, 16),
								},
								DragDetector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 877),
									ImageRectSize = Vector2.new(16, 16),
								},
								DrawOnTop = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 910),
									ImageRectSize = Vector2.new(16, 16),
								},
								DropdownArrow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 943),
									ImageRectSize = Vector2.new(16, 16),
								},
								Duplicate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 976),
									ImageRectSize = Vector2.new(16, 16),
								},
								EchoSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 283),
									ImageRectSize = Vector2.new(16, 16),
								},
								EditPivot = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 316),
									ImageRectSize = Vector2.new(16, 16),
								},
								Effects = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 349),
									ImageRectSize = Vector2.new(16, 16),
								},
								Enum = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 382),
									ImageRectSize = Vector2.new(16, 16),
								},
								EnumMember = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 415),
									ImageRectSize = Vector2.new(16, 16),
								},
								EqualizerSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 447),
									ImageRectSize = Vector2.new(16, 16),
								},
								Error = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 480),
									ImageRectSize = Vector2.new(16, 16),
								},
								Event = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 512),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExitGame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 545),
									ImageRectSize = Vector2.new(16, 16),
								},
								Expand = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 578),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExpandAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 611),
									ImageRectSize = Vector2.new(16, 16),
								},
								Explorer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 644),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExplorerSelectAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 677),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExplorerSelectAllOld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 710),
									ImageRectSize = Vector2.new(16, 16),
								},
								Explosion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 743),
									ImageRectSize = Vector2.new(16, 16),
								},
								FaceControls = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 776),
									ImageRectSize = Vector2.new(16, 16),
								},
								Favorited = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 795),
									ImageRectSize = Vector2.new(16, 16),
								},
								FavoritesTab_Default = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 278),
									ImageRectSize = Vector2.new(16, 15),
								},
								FavoritesTab_Selected = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 327),
									ImageRectSize = Vector2.new(16, 15),
								},
								Field = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 828),
									ImageRectSize = Vector2.new(16, 16),
								},
								File = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 861),
									ImageRectSize = Vector2.new(16, 16),
								},
								Filter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 894),
									ImageRectSize = Vector2.new(16, 16),
								},
								FilterWithDropdown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 927),
									ImageRectSize = Vector2.new(16, 16),
								},
								Find = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 960),
									ImageRectSize = Vector2.new(16, 16),
								},
								FindAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(264, 993),
									ImageRectSize = Vector2.new(16, 16),
								},
								FindNext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 300),
									ImageRectSize = Vector2.new(16, 16),
								},
								FindPrevious = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 333),
									ImageRectSize = Vector2.new(16, 16),
								},
								Fire = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 366),
									ImageRectSize = Vector2.new(16, 16),
								},
								FlangeSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 399),
									ImageRectSize = Vector2.new(16, 16),
								},
								Folder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 432),
									ImageRectSize = Vector2.new(16, 16),
								},
								ForceField = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 464),
									ImageRectSize = Vector2.new(16, 16),
								},
								FormatDocument = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 497),
									ImageRectSize = Vector2.new(16, 16),
								},
								FormatSelection = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 529),
									ImageRectSize = Vector2.new(16, 16),
								},
								Frame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 562),
									ImageRectSize = Vector2.new(16, 16),
								},
								FullScreen = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 595),
									ImageRectSize = Vector2.new(16, 16),
								},
								Function = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 628),
									ImageRectSize = Vector2.new(16, 16),
								},
								Fwd = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 661),
									ImageRectSize = Vector2.new(16, 16),
								},
								Gallery = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 694),
									ImageRectSize = Vector2.new(16, 16),
								},
								GameSettings = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 727),
									ImageRectSize = Vector2.new(16, 16),
								},
								GlobalWindControl = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 760),
									ImageRectSize = Vector2.new(16, 16),
								},
								GoToLine = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 793),
									ImageRectSize = Vector2.new(16, 16),
								},
								GridMaterial = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 812),
									ImageRectSize = Vector2.new(16, 16),
								},
								GroundController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 845),
									ImageRectSize = Vector2.new(16, 16),
								},
								Group = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 878),
									ImageRectSize = Vector2.new(16, 16),
								},
								Handles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 911),
									ImageRectSize = Vector2.new(16, 16),
								},
								HapticService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 944),
									ImageRectSize = Vector2.new(16, 16),
								},
								HeightmapImporterService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 977),
									ImageRectSize = Vector2.new(16, 16),
								},
								Highlight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 317),
									ImageRectSize = Vector2.new(16, 16),
								},
								Hinge = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 350),
									ImageRectSize = Vector2.new(16, 16),
								},
								HingeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 383),
									ImageRectSize = Vector2.new(16, 16),
								},
								HorizontalDoubleArrow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 416),
									ImageRectSize = Vector2.new(16, 16),
								},
								Hover = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 449),
									ImageRectSize = Vector2.new(16, 16),
								},
								Humanoid = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 481),
									ImageRectSize = Vector2.new(16, 16),
								},
								HumanoidDescription = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 514),
									ImageRectSize = Vector2.new(16, 16),
								},
								IKControl = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 546),
									ImageRectSize = Vector2.new(16, 16),
								},
								ImageButton = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 579),
									ImageRectSize = Vector2.new(16, 16),
								},
								ImageHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 612),
									ImageRectSize = Vector2.new(16, 16),
								},
								ImageLabel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 645),
									ImageRectSize = Vector2.new(16, 16),
								},
								InnerCage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 678),
									ImageRectSize = Vector2.new(16, 16),
								},
								InsertObject = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 711),
									ImageRectSize = Vector2.new(16, 16),
								},
								Interface = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 744),
									ImageRectSize = Vector2.new(16, 16),
								},
								IntersectOperation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 777),
									ImageRectSize = Vector2.new(16, 16),
								},
								InvalidBreakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 810),
									ImageRectSize = Vector2.new(16, 16),
								},
								InvalidLogpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 829),
									ImageRectSize = Vector2.new(16, 16),
								},
								InventoryTab_Default = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(980, 997),
									ImageRectSize = Vector2.new(16, 18),
								},
								InventoryTab_Selected = {
									Image = "rbxassetid://14874018310",
									ImageRectOffset = Vector2.new(997, 997),
									ImageRectSize = Vector2.new(16, 18),
								},
								Italic_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 862),
									ImageRectSize = Vector2.new(16, 16),
								},
								Italic_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 895),
									ImageRectSize = Vector2.new(16, 16),
								},
								Keyword = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 928),
									ImageRectSize = Vector2.new(16, 16),
								},
								LegacyClientRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 961),
									ImageRectSize = Vector2.new(16, 16),
								},
								LegacyServerRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(297, 994),
									ImageRectSize = Vector2.new(16, 16),
								},
								Lighting = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 334),
									ImageRectSize = Vector2.new(16, 16),
								},
								LineForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 367),
									ImageRectSize = Vector2.new(16, 16),
								},
								LineHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 400),
									ImageRectSize = Vector2.new(16, 16),
								},
								LinearVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 433),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalFile = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 466),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalScript = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 498),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalizationService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 531),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalizationTable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 563),
									ImageRectSize = Vector2.new(16, 16),
								},
								Lock = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 596),
									ImageRectSize = Vector2.new(16, 16),
								},
								LockAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 629),
									ImageRectSize = Vector2.new(16, 16),
								},
								LockCursor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 662),
									ImageRectSize = Vector2.new(16, 16),
								},
								LockTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 695),
									ImageRectSize = Vector2.new(16, 16),
								},
								Logpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 728),
									ImageRectSize = Vector2.new(16, 16),
								},
								LogpointDisabled = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 761),
									ImageRectSize = Vector2.new(16, 16),
								},
								ManagePlugins = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 794),
									ImageRectSize = Vector2.new(16, 16),
								},
								MarketplaceIcon = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 827),
									ImageRectSize = Vector2.new(16, 16),
								},
								MarketplaceIcon_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 846),
									ImageRectSize = Vector2.new(16, 16),
								},
								MarketplaceIcon_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 879),
									ImageRectSize = Vector2.new(16, 16),
								},
								MatchCase = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 912),
									ImageRectSize = Vector2.new(16, 16),
								},
								MatchWholeWord = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 945),
									ImageRectSize = Vector2.new(16, 16),
								},
								Material = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 978),
									ImageRectSize = Vector2.new(16, 16),
								},
								MaterialService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 351),
									ImageRectSize = Vector2.new(16, 16),
								},
								MaterialVariant = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 384),
									ImageRectSize = Vector2.new(16, 16),
								},
								MemoryStoreService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 417),
									ImageRectSize = Vector2.new(16, 16),
								},
								MeshPart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 450),
									ImageRectSize = Vector2.new(16, 16),
								},
								MeshVisibility = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 483),
									ImageRectSize = Vector2.new(16, 16),
								},
								Meshparts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 515),
									ImageRectSize = Vector2.new(16, 16),
								},
								MessagingService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 548),
									ImageRectSize = Vector2.new(16, 16),
								},
								Method = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 580),
									ImageRectSize = Vector2.new(16, 16),
								},
								Model = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 613),
									ImageRectSize = Vector2.new(16, 16),
								},
								Modelgroups = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 646),
									ImageRectSize = Vector2.new(16, 16),
								},
								Modified = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 679),
									ImageRectSize = Vector2.new(16, 16),
								},
								ModifiedPackage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 712),
									ImageRectSize = Vector2.new(16, 16),
								},
								Module = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 745),
									ImageRectSize = Vector2.new(16, 16),
								},
								ModuleScript = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 778),
									ImageRectSize = Vector2.new(16, 16),
								},
								More = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 811),
									ImageRectSize = Vector2.new(16, 16),
								},
								Motor6D = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 844),
									ImageRectSize = Vector2.new(16, 16),
								},
								Move = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 863),
									ImageRectSize = Vector2.new(16, 16),
								},
								Move_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 896),
									ImageRectSize = Vector2.new(16, 16),
								},
								Mute = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 929),
									ImageRectSize = Vector2.new(16, 16),
								},
								NegateOperation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 962),
									ImageRectSize = Vector2.new(16, 16),
								},
								NetworkClient = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(330, 995),
									ImageRectSize = Vector2.new(16, 16),
								},
								NewFile = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 368),
									ImageRectSize = Vector2.new(16, 16),
								},
								NextResult = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 401),
									ImageRectSize = Vector2.new(16, 16),
								},
								NoCollision = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 434),
									ImageRectSize = Vector2.new(16, 16),
								},
								NoCollisionConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 467),
									ImageRectSize = Vector2.new(16, 16),
								},
								NotFavorited = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 376),
									ImageRectSize = Vector2.new(16, 15),
								},
								NotificationBell = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 500),
									ImageRectSize = Vector2.new(16, 16),
								},
								NotificationBellNew = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 532),
									ImageRectSize = Vector2.new(16, 16),
								},
								ObjectBrowser = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 565),
									ImageRectSize = Vector2.new(16, 16),
								},
								Open = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 597),
									ImageRectSize = Vector2.new(16, 16),
								},
								OpenHandPointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 630),
									ImageRectSize = Vector2.new(16, 16),
								},
								OpenScriptFunctionFilter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 663),
									ImageRectSize = Vector2.new(16, 16),
								},
								Operator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 696),
									ImageRectSize = Vector2.new(16, 16),
								},
								OptionsDots = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 729),
									ImageRectSize = Vector2.new(16, 16),
								},
								OuterCage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 762),
									ImageRectSize = Vector2.new(16, 16),
								},
								Outline = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 795),
									ImageRectSize = Vector2.new(16, 16),
								},
								OutlineBoundingBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 828),
									ImageRectSize = Vector2.new(16, 16),
								},
								Output = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 861),
									ImageRectSize = Vector2.new(16, 16),
								},
								Package = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 880),
									ImageRectSize = Vector2.new(16, 16),
								},
								PackageLink = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 913),
									ImageRectSize = Vector2.new(16, 16),
								},
								PackageLinkAttatchment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 946),
									ImageRectSize = Vector2.new(16, 16),
								},
								Packages = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 979),
									ImageRectSize = Vector2.new(16, 16),
								},
								PanCamera = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 385),
									ImageRectSize = Vector2.new(16, 16),
								},
								Pants = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 418),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 451),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Block = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 484),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_CornerWedge = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 517),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Cylinder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 549),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Sphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 582),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Wedge = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 614),
									ImageRectSize = Vector2.new(16, 16),
								},
								ParticleEmitter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 647),
									ImageRectSize = Vector2.new(16, 16),
								},
								Paste = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 680),
									ImageRectSize = Vector2.new(16, 16),
								},
								PathfindingLink = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 713),
									ImageRectSize = Vector2.new(16, 16),
								},
								PathfindingModifier = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 746),
									ImageRectSize = Vector2.new(16, 16),
								},
								PathfindingService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 779),
									ImageRectSize = Vector2.new(16, 16),
								},
								Pause = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 812),
									ImageRectSize = Vector2.new(16, 16),
								},
								Performance = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 845),
									ImageRectSize = Vector2.new(16, 16),
								},
								PitchShiftSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 878),
									ImageRectSize = Vector2.new(16, 16),
								},
								Place = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 897),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlaceCloud = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 930),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlaceLocal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 963),
									ImageRectSize = Vector2.new(16, 16),
								},
								Placeholder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(363, 996),
									ImageRectSize = Vector2.new(16, 16),
								},
								Plane = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 402),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlaneConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 435),
									ImageRectSize = Vector2.new(16, 16),
								},
								Play = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 468),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlayHere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 501),
									ImageRectSize = Vector2.new(16, 16),
								},
								Player = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 534),
									ImageRectSize = Vector2.new(16, 16),
								},
								Players = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 566),
									ImageRectSize = Vector2.new(16, 16),
								},
								PluginGuiService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 599),
									ImageRectSize = Vector2.new(16, 16),
								},
								PluginRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 631),
									ImageRectSize = Vector2.new(16, 16),
								},
								PluginsFolder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 664),
									ImageRectSize = Vector2.new(16, 16),
								},
								PointLight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 697),
									ImageRectSize = Vector2.new(16, 16),
								},
								Pointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 730),
									ImageRectSize = Vector2.new(16, 16),
								},
								PreviousResult = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 763),
									ImageRectSize = Vector2.new(16, 16),
								},
								PreviousResultOld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 796),
									ImageRectSize = Vector2.new(16, 16),
								},
								Prismatic = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 829),
									ImageRectSize = Vector2.new(16, 16),
								},
								PrismaticConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 862),
									ImageRectSize = Vector2.new(16, 16),
								},
								Properties = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 895),
									ImageRectSize = Vector2.new(16, 16),
								},
								Property = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 914),
									ImageRectSize = Vector2.new(16, 16),
								},
								ProximityPrompt = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 947),
									ImageRectSize = Vector2.new(16, 16),
								},
								PublishService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 980),
									ImageRectSize = Vector2.new(16, 16),
								},
								QuickOpen = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 419),
									ImageRectSize = Vector2.new(16, 16),
								},
								QuickOpenActions = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 452),
									ImageRectSize = Vector2.new(16, 16),
								},
								Redo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 485),
									ImageRectSize = Vector2.new(16, 16),
								},
								Reference = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 518),
									ImageRectSize = Vector2.new(16, 16),
								},
								Refresh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 551),
									ImageRectSize = Vector2.new(16, 16),
								},
								RefreshOld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 583),
									ImageRectSize = Vector2.new(16, 16),
								},
								RegularExpression = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 616),
									ImageRectSize = Vector2.new(16, 16),
								},
								RemoteEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 648),
									ImageRectSize = Vector2.new(16, 16),
								},
								RemoteFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 681),
									ImageRectSize = Vector2.new(16, 16),
								},
								RenderingTest = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 714),
									ImageRectSize = Vector2.new(16, 16),
								},
								Replace = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 747),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReplicatedFirst = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 780),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReplicatedScriptService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 813),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReplicatedStorage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 846),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResetPivot = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 879),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResizeDiagonal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 912),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResizeHorizontal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 931),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResizeVertical = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 964),
									ImageRectSize = Vector2.new(16, 16),
								},
								Resume = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(396, 997),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReverbSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 436),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rigid = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 469),
									ImageRectSize = Vector2.new(16, 16),
								},
								RigidConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 502),
									ImageRectSize = Vector2.new(16, 16),
								},
								RobloxPluginGuiService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 535),
									ImageRectSize = Vector2.new(16, 16),
								},
								RocketPropulsion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 568),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rod = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 600),
									ImageRectSize = Vector2.new(16, 16),
								},
								RodConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 633),
									ImageRectSize = Vector2.new(16, 16),
								},
								RopeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 665),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rotate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 698),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rotate_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 731),
									ImageRectSize = Vector2.new(16, 16),
								},
								Run = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 764),
									ImageRectSize = Vector2.new(16, 16),
								},
								RunScript = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 797),
									ImageRectSize = Vector2.new(16, 16),
								},
								Save = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 830),
									ImageRectSize = Vector2.new(16, 16),
								},
								Scale = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 863),
									ImageRectSize = Vector2.new(16, 16),
								},
								Scale_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 896),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScreenGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 929),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScreenShot = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 948),
									ImageRectSize = Vector2.new(16, 16),
								},
								Script = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 981),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScriptAnalysis = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 453),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScriptPerformance = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 486),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScriptRecovery = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 519),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollbarDown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 552),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollbarTriangle = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 585),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollbarUp = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 617),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollingFrame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 650),
									ImageRectSize = Vector2.new(16, 16),
								},
								Seat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 682),
									ImageRectSize = Vector2.new(16, 16),
								},
								Select = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 715),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectAll = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 748),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectChildren = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 781),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectText = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 814),
									ImageRectSize = Vector2.new(16, 16),
								},
								Select_P = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 847),
									ImageRectSize = Vector2.new(16, 16),
								},
								Selected_Workspace = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 880),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectionBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 913),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectionSphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 946),
									ImageRectSize = Vector2.new(16, 16),
								},
								Separate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 965),
									ImageRectSize = Vector2.new(16, 16),
								},
								Server = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(429, 998),
									ImageRectSize = Vector2.new(16, 16),
								},
								ServerRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 470),
									ImageRectSize = Vector2.new(16, 16),
								},
								ServerScriptService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 503),
									ImageRectSize = Vector2.new(16, 16),
								},
								ServerStorage = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 536),
									ImageRectSize = Vector2.new(16, 16),
								},
								Service = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 569),
									ImageRectSize = Vector2.new(16, 16),
								},
								Settings = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 602),
									ImageRectSize = Vector2.new(16, 16),
								},
								Shirt = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 634),
									ImageRectSize = Vector2.new(16, 16),
								},
								ShirtGraphic = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 667),
									ImageRectSize = Vector2.new(16, 16),
								},
								ShowGrid = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 699),
									ImageRectSize = Vector2.new(16, 16),
								},
								ShowWelds = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 732),
									ImageRectSize = Vector2.new(16, 16),
								},
								SkinnedMeshPart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 765),
									ImageRectSize = Vector2.new(16, 16),
								},
								Sky = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 798),
									ImageRectSize = Vector2.new(16, 16),
								},
								Smoke = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 831),
									ImageRectSize = Vector2.new(16, 16),
								},
								Snap = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 864),
									ImageRectSize = Vector2.new(16, 16),
								},
								Snippet = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 897),
									ImageRectSize = Vector2.new(16, 16),
								},
								SocialService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 930),
									ImageRectSize = Vector2.new(16, 16),
								},
								Sound = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 963),
									ImageRectSize = Vector2.new(16, 16),
								},
								SoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 982),
									ImageRectSize = Vector2.new(16, 16),
								},
								SoundGroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 487),
									ImageRectSize = Vector2.new(16, 16),
								},
								SoundService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 520),
									ImageRectSize = Vector2.new(16, 16),
								},
								Sparkles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 553),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpawnLocation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 586),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpecialMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 619),
									ImageRectSize = Vector2.new(16, 16),
								},
								SphereHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 651),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpotLight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 684),
									ImageRectSize = Vector2.new(16, 16),
								},
								Spring = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 716),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpringConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 749),
									ImageRectSize = Vector2.new(16, 16),
								},
								StandalonePluginScripts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 782),
									ImageRectSize = Vector2.new(16, 16),
								},
								StartServerAndClient = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 815),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterCharacterScripts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 848),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 881),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterPack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 914),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterPlayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 947),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterPlayerScripts = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 980),
									ImageRectSize = Vector2.new(16, 16),
								},
								StepInto = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(462, 999),
									ImageRectSize = Vector2.new(16, 16),
								},
								StepOut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 504),
									ImageRectSize = Vector2.new(16, 16),
								},
								StepOver = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 537),
									ImageRectSize = Vector2.new(16, 16),
								},
								Stop = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 570),
									ImageRectSize = Vector2.new(16, 16),
								},
								Strikethrough_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 603),
									ImageRectSize = Vector2.new(16, 16),
								},
								Strikethrough_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 636),
									ImageRectSize = Vector2.new(16, 16),
								},
								Struct = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 668),
									ImageRectSize = Vector2.new(16, 16),
								},
								SunRaysEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 701),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceAppearance = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 733),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 766),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceLight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 799),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceSelection = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 832),
									ImageRectSize = Vector2.new(16, 16),
								},
								SwimController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 865),
									ImageRectSize = Vector2.new(16, 16),
								},
								SwitchWindows = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 898),
									ImageRectSize = Vector2.new(16, 16),
								},
								TagEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 931),
									ImageRectSize = Vector2.new(16, 16),
								},
								TaskScheduler = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 964),
									ImageRectSize = Vector2.new(16, 16),
								},
								Team = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(495, 997),
									ImageRectSize = Vector2.new(16, 16),
								},
								TeamCreate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 521),
									ImageRectSize = Vector2.new(16, 16),
								},
								TeamTest = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 554),
									ImageRectSize = Vector2.new(16, 16),
								},
								Teams = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 587),
									ImageRectSize = Vector2.new(16, 16),
								},
								Terrain = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 620),
									ImageRectSize = Vector2.new(16, 16),
								},
								TerrainDetail = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 653),
									ImageRectSize = Vector2.new(16, 16),
								},
								TerrainEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 685),
									ImageRectSize = Vector2.new(16, 16),
								},
								TestService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 718),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 750),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextBoxService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 783),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextButton = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 816),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextChannel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 849),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextChatCommand = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 882),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextChatService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 915),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextLabel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 948),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextString = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 981),
									ImageRectSize = Vector2.new(16, 16),
								},
								Texture = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 538),
									ImageRectSize = Vector2.new(16, 16),
								},
								Tool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 571),
									ImageRectSize = Vector2.new(16, 16),
								},
								Toolbox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 604),
									ImageRectSize = Vector2.new(16, 16),
								},
								Torque = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 637),
									ImageRectSize = Vector2.new(16, 16),
								},
								TorsionSpring = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 670),
									ImageRectSize = Vector2.new(16, 16),
								},
								TorsionSpringConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 702),
									ImageRectSize = Vector2.new(16, 16),
								},
								Trail = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 735),
									ImageRectSize = Vector2.new(16, 16),
								},
								Transform = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 767),
									ImageRectSize = Vector2.new(16, 16),
								},
								Transparency = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 800),
									ImageRectSize = Vector2.new(16, 16),
								},
								TremoloSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 833),
									ImageRectSize = Vector2.new(16, 16),
								},
								TrussPart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 866),
									ImageRectSize = Vector2.new(16, 16),
								},
								TypeParameter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 899),
									ImageRectSize = Vector2.new(16, 16),
								},
								UGCValidationService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 932),
									ImageRectSize = Vector2.new(16, 16),
								},
								UI = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 965),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIAspectRatioConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(528, 998),
									ImageRectSize = Vector2.new(16, 16),
								},
								UICorner = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 555),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIGradient = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 588),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIGridLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 621),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIListLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 654),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIOff = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 687),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIOn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 719),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIPadding = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 752),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIPageLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 784),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIScale = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 817),
									ImageRectSize = Vector2.new(16, 16),
								},
								UISizeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 850),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIStroke = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 883),
									ImageRectSize = Vector2.new(16, 16),
								},
								UITableLayout = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 916),
									ImageRectSize = Vector2.new(16, 16),
								},
								UITextSizeConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 949),
									ImageRectSize = Vector2.new(16, 16),
								},
								Underline_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 982),
									ImageRectSize = Vector2.new(16, 16),
								},
								Underline_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 572),
									ImageRectSize = Vector2.new(16, 16),
								},
								Undo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 605),
									ImageRectSize = Vector2.new(16, 16),
								},
								UndockPreviewWindow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 638),
									ImageRectSize = Vector2.new(16, 16),
								},
								Ungroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 671),
									ImageRectSize = Vector2.new(16, 16),
								},
								UnionOperation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 704),
									ImageRectSize = Vector2.new(16, 16),
								},
								Unit = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 736),
									ImageRectSize = Vector2.new(16, 16),
								},
								Universal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 769),
									ImageRectSize = Vector2.new(16, 16),
								},
								UniversalConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 801),
									ImageRectSize = Vector2.new(16, 16),
								},
								Unlock = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 834),
									ImageRectSize = Vector2.new(16, 16),
								},
								UnlockCursor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 867),
									ImageRectSize = Vector2.new(16, 16),
								},
								UpdateAvailable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 900),
									ImageRectSize = Vector2.new(16, 16),
								},
								UserService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 933),
									ImageRectSize = Vector2.new(16, 16),
								},
								Value = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 966),
									ImageRectSize = Vector2.new(16, 16),
								},
								Variable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(561, 999),
									ImageRectSize = Vector2.new(16, 16),
								},
								VectorForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 589),
									ImageRectSize = Vector2.new(16, 16),
								},
								VehicleSeat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 622),
									ImageRectSize = Vector2.new(16, 16),
								},
								VideoFrame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 655),
									ImageRectSize = Vector2.new(16, 16),
								},
								VideoRecord = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 688),
									ImageRectSize = Vector2.new(16, 16),
								},
								ViewSelector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 721),
									ImageRectSize = Vector2.new(16, 16),
								},
								ViewportFrame = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 753),
									ImageRectSize = Vector2.new(16, 16),
								},
								VirtualUser = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 786),
									ImageRectSize = Vector2.new(16, 16),
								},
								VoiceChannel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 818),
									ImageRectSize = Vector2.new(16, 16),
								},
								VoiceChatService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 851),
									ImageRectSize = Vector2.new(16, 16),
								},
								Voicechat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 884),
									ImageRectSize = Vector2.new(16, 16),
								},
								Warning = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 917),
									ImageRectSize = Vector2.new(16, 16),
								},
								Watch = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 950),
									ImageRectSize = Vector2.new(16, 16),
								},
								WedgePart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 983),
									ImageRectSize = Vector2.new(16, 16),
								},
								Weld = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 606),
									ImageRectSize = Vector2.new(16, 16),
								},
								WeldConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 639),
									ImageRectSize = Vector2.new(16, 16),
								},
								Wire = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 672),
									ImageRectSize = Vector2.new(16, 16),
								},
								WireframeHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 705),
									ImageRectSize = Vector2.new(16, 16),
								},
								WireframeRendering = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 738),
									ImageRectSize = Vector2.new(16, 16),
								},
								Workspace = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 770),
									ImageRectSize = Vector2.new(16, 16),
								},
								WorldModel = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 803),
									ImageRectSize = Vector2.new(16, 16),
								},
								WrapLayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 835),
									ImageRectSize = Vector2.new(16, 16),
								},
								WrapTarget = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 868),
									ImageRectSize = Vector2.new(16, 16),
								},
								ZoomIn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 901),
									ImageRectSize = Vector2.new(16, 16),
								},
								ZoomOut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 934),
									ImageRectSize = Vector2.new(16, 16),
								},
								ZoomTo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 967),
									ImageRectSize = Vector2.new(16, 16),
								},
							},
						},
					},
				},
			},
		},
	},
}