-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Assets = {
		Qt = {
			icons = {
				Light = {
					Roblox = {
						["16"] = {
							["1x"] = {
								ACCodeSnippet = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(594, 1000),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACEnum = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 623),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 656),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 689),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACKeyword = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 722),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACProperty = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 755),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACText = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 787),
									ImageRectSize = Vector2.new(16, 16),
								},
								ACVariable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 820),
									ImageRectSize = Vector2.new(16, 16),
								},
								Accessory = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 852),
									ImageRectSize = Vector2.new(16, 16),
								},
								AccessoryFittingTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 885),
									ImageRectSize = Vector2.new(16, 16),
								},
								Actor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 918),
									ImageRectSize = Vector2.new(16, 16),
								},
								AdGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 951),
									ImageRectSize = Vector2.new(16, 16),
								},
								AdPortal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 984),
									ImageRectSize = Vector2.new(16, 16),
								},
								Add = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 640),
									ImageRectSize = Vector2.new(16, 16),
								},
								AddNoBorder = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 673),
									ImageRectSize = Vector2.new(16, 16),
								},
								AddWatch = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 706),
									ImageRectSize = Vector2.new(16, 16),
								},
								AirController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 739),
									ImageRectSize = Vector2.new(16, 16),
								},
								AlignOrientation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 772),
									ImageRectSize = Vector2.new(16, 16),
								},
								AlignPosition = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 804),
									ImageRectSize = Vector2.new(16, 16),
								},
								AlignTool = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 837),
									ImageRectSize = Vector2.new(16, 16),
								},
								Anchor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 869),
									ImageRectSize = Vector2.new(16, 16),
								},
								AngularVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 902),
									ImageRectSize = Vector2.new(16, 16),
								},
								Animation = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 935),
									ImageRectSize = Vector2.new(16, 16),
								},
								AnimationConstraint = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 425),
									ImageRectSize = Vector2.new(16, 15),
								},
								AnimationController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 968),
									ImageRectSize = Vector2.new(16, 16),
								},
								AnimationEditor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(627, 1001),
									ImageRectSize = Vector2.new(16, 16),
								},
								AnimationFromVideoCreatorService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 657),
									ImageRectSize = Vector2.new(16, 16),
								},
								Animator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 690),
									ImageRectSize = Vector2.new(16, 16),
								},
								ArcHandles = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 723),
									ImageRectSize = Vector2.new(16, 16),
								},
								ArrowDown = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 756),
									ImageRectSize = Vector2.new(16, 16),
								},
								ArrowRight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 789),
									ImageRectSize = Vector2.new(16, 16),
								},
								AssetManager = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 821),
									ImageRectSize = Vector2.new(16, 16),
								},
								Atmosphere = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 854),
									ImageRectSize = Vector2.new(16, 16),
								},
								Attachment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 886),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioAnalyzer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 919),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioChorus = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 952),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioCompressor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 985),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioDeviceInput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 674),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioDeviceOutput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 707),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioDistortion = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 740),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioEcho = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 773),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioEmitter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 806),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioEqualizer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 838),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioFader = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 871),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioFlanger = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 903),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioListener = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 936),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioPitchShifter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 969),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioPlayer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(660, 1002),
									ImageRectSize = Vector2.new(16, 16),
								},
								AudioReverb = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 691),
									ImageRectSize = Vector2.new(16, 16),
								},
								AutoWeight = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 724),
									ImageRectSize = Vector2.new(16, 16),
								},
								AutoupdateOn = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 757),
									ImageRectSize = Vector2.new(16, 16),
								},
								AvatarEditorService = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 790),
									ImageRectSize = Vector2.new(16, 16),
								},
								AvatarImporter = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 823),
									ImageRectSize = Vector2.new(16, 16),
								},
								Back = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 855),
									ImageRectSize = Vector2.new(16, 16),
								},
								Backpack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 888),
									ImageRectSize = Vector2.new(16, 16),
								},
								BallSocket = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 920),
									ImageRectSize = Vector2.new(16, 16),
								},
								BallSocketConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 953),
									ImageRectSize = Vector2.new(16, 16),
								},
								BasePlate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 986),
									ImageRectSize = Vector2.new(16, 16),
								},
								Beam = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 708),
									ImageRectSize = Vector2.new(16, 16),
								},
								BillboardGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 741),
									ImageRectSize = Vector2.new(16, 16),
								},
								BindableEvent = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 774),
									ImageRectSize = Vector2.new(16, 16),
								},
								BindableFunction = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 807),
									ImageRectSize = Vector2.new(16, 16),
								},
								BlockMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 840),
									ImageRectSize = Vector2.new(16, 16),
								},
								BloomEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 872),
									ImageRectSize = Vector2.new(16, 16),
								},
								BlurEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 905),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyAngularVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 937),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyColors = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 970),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyForce = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(693, 1003),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyGyro = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 725),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyPosition = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 758),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyThrust = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 791),
									ImageRectSize = Vector2.new(16, 16),
								},
								BodyVelocity = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 824),
									ImageRectSize = Vector2.new(16, 16),
								},
								Bold_Default = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 857),
									ImageRectSize = Vector2.new(16, 16),
								},
								Bold_Selected = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 889),
									ImageRectSize = Vector2.new(16, 16),
								},
								Bone = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 922),
									ImageRectSize = Vector2.new(16, 16),
								},
								BoolValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 954),
									ImageRectSize = Vector2.new(16, 16),
								},
								BoundingBox = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 987),
									ImageRectSize = Vector2.new(16, 16),
								},
								BoxHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 742),
									ImageRectSize = Vector2.new(16, 16),
								},
								Breakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 775),
									ImageRectSize = Vector2.new(16, 16),
								},
								Breakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 808),
									ImageRectSize = Vector2.new(16, 16),
								},
								BrickColorValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 841),
									ImageRectSize = Vector2.new(16, 16),
								},
								BubbleChatConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 874),
									ImageRectSize = Vector2.new(16, 16),
								},
								Buggaroo = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 906),
									ImageRectSize = Vector2.new(16, 16),
								},
								CFrameValue = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 939),
									ImageRectSize = Vector2.new(16, 16),
								},
								CageMode = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 971),
									ImageRectSize = Vector2.new(16, 16),
								},
								CageVisibility = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(726, 1004),
									ImageRectSize = Vector2.new(16, 16),
								},
								CallStack = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 759),
									ImageRectSize = Vector2.new(16, 16),
								},
								Camera = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 792),
									ImageRectSize = Vector2.new(16, 16),
								},
								CameraToMannequin = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 825),
									ImageRectSize = Vector2.new(16, 16),
								},
								CanvasGroup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 858),
									ImageRectSize = Vector2.new(16, 16),
								},
								CharacterControllerManager = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 891),
									ImageRectSize = Vector2.new(16, 16),
								},
								CharacterMesh = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 923),
									ImageRectSize = Vector2.new(16, 16),
								},
								Chat = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 956),
									ImageRectSize = Vector2.new(16, 16),
								},
								ChatInputBarConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 988),
									ImageRectSize = Vector2.new(16, 16),
								},
								ChatWindowConfiguration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 776),
									ImageRectSize = Vector2.new(16, 16),
								},
								ChorusSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 809),
									ImageRectSize = Vector2.new(16, 16),
								},
								Class = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 842),
									ImageRectSize = Vector2.new(16, 16),
								},
								Cleanup = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 875),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClearInput = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 908),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClearStats = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 940),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClickDetector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 973),
									ImageRectSize = Vector2.new(16, 16),
								},
								Client = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(759, 1005),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClientReplicator = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 793),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClientRunContext = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 826),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClimbController = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 859),
									ImageRectSize = Vector2.new(16, 16),
								},
								CloseWidget = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 892),
									ImageRectSize = Vector2.new(16, 16),
								},
								ClosedHandPointer = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 925),
									ImageRectSize = Vector2.new(16, 16),
								},
								Clouds = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 957),
									ImageRectSize = Vector2.new(16, 16),
								},
								Collapse = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(792, 990),
									ImageRectSize = Vector2.new(16, 16),
								},
								CollisionGroups = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 810),
									ImageRectSize = Vector2.new(16, 16),
								},
								Color = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 843),
									ImageRectSize = Vector2.new(16, 16),
								},
								ColorCorrectionEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 876),
									ImageRectSize = Vector2.new(16, 16),
								},
								ColorPicker = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 909),
									ImageRectSize = Vector2.new(16, 16),
								},
								CommandBar = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 942),
									ImageRectSize = Vector2.new(16, 16),
								},
								CompressorSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 974),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConditionalBreakpoint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 827),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConditionalBreakpointDisabled = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 860),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConeHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 893),
									ImageRectSize = Vector2.new(16, 16),
								},
								Configuration = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 926),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConnectionFailed = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 959),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConnectionStable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(825, 991),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConnectionUnstable = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 844),
									ImageRectSize = Vector2.new(16, 16),
								},
								Constant = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 877),
									ImageRectSize = Vector2.new(16, 16),
								},
								ConstraintDetails = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 910),
									ImageRectSize = Vector2.new(16, 16),
								},
								Constructor = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 943),
									ImageRectSize = Vector2.new(16, 16),
								},
								Copy = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 976),
									ImageRectSize = Vector2.new(16, 16),
								},
								CoreGui = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 861),
									ImageRectSize = Vector2.new(16, 16),
								},
								CornerWedgePart = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 894),
									ImageRectSize = Vector2.new(16, 16),
								},
								CreateConstraints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 927),
									ImageRectSize = Vector2.new(16, 16),
								},
								Cut = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 960),
									ImageRectSize = Vector2.new(16, 16),
								},
								CylinderHandleAdornment = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(858, 993),
									ImageRectSize = Vector2.new(16, 16),
								},
								Cylindrical = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 878),
									ImageRectSize = Vector2.new(16, 16),
								},
								CylindricalConstraint = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 911),
									ImageRectSize = Vector2.new(16, 16),
								},
								Decal = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 944),
									ImageRectSize = Vector2.new(16, 16),
								},
								Delete = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 977),
									ImageRectSize = Vector2.new(16, 16),
								},
								DeleteAllBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 895),
									ImageRectSize = Vector2.new(16, 16),
								},
								DeleteSelectedBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 928),
									ImageRectSize = Vector2.new(16, 16),
								},
								DepthOfFieldEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 961),
									ImageRectSize = Vector2.new(16, 16),
								},
								Device = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(891, 994),
									ImageRectSize = Vector2.new(16, 16),
								},
								DeviceSafeArea = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 912),
									ImageRectSize = Vector2.new(16, 16),
								},
								Dialog = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 945),
									ImageRectSize = Vector2.new(16, 16),
								},
								DialogChoice = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 978),
									ImageRectSize = Vector2.new(16, 16),
								},
								DisableAllBreakpoints = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 929),
									ImageRectSize = Vector2.new(16, 16),
								},
								DistortionSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 962),
									ImageRectSize = Vector2.new(16, 16),
								},
								Download = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(924, 995),
									ImageRectSize = Vector2.new(16, 16),
								},
								Draft = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 946),
									ImageRectSize = Vector2.new(16, 16),
								},
								DragDetector = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 979),
									ImageRectSize = Vector2.new(16, 16),
								},
								DrawOnTop = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 963),
									ImageRectSize = Vector2.new(16, 16),
								},
								DropdownArrow = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(957, 996),
									ImageRectSize = Vector2.new(16, 16),
								},
								Duplicate = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 980),
									ImageRectSize = Vector2.new(16, 16),
								},
								EchoSoundEffect = {
									Image = "rbxassetid://14874019542",
									ImageRectOffset = Vector2.new(990, 997),
									ImageRectSize = Vector2.new(16, 16),
								},
								EditPivot = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								Effects = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								Enum = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								EnumMember = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								EqualizerSoundEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Error = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Event = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExitGame = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Expand = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExpandAll = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Explorer = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExplorerSelectAll = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								ExplorerSelectAllOld = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 474),
									ImageRectSize = Vector2.new(16, 15),
								},
								Explosion = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								FaceControls = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Favorited = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								FavoritesTab_Default = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 523),
									ImageRectSize = Vector2.new(16, 15),
								},
								FavoritesTab_Selected = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 572),
									ImageRectSize = Vector2.new(16, 15),
								},
								Field = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								File = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Filter = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								FilterWithDropdown = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Find = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								FindAll = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								FindNext = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								FindPrevious = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Fire = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								FlangeSoundEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Folder = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								ForceField = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								FormatDocument = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								FormatSelection = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								Frame = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								FullScreen = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Function = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Fwd = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Gallery = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								GameSettings = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								GlobalWindControl = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								GoToLine = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								GridMaterial = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								GroundController = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Group = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Handles = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								HapticService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								HeightmapImporterService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Highlight = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								Hinge = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								HingeConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								HorizontalDoubleArrow = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Hover = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Humanoid = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								HumanoidDescription = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								IKControl = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								ImageButton = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								ImageHandleAdornment = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								ImageLabel = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								InnerCage = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								InsertObject = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								Interface = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								IntersectOperation = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								InvalidBreakpoint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								InvalidLogpoint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								InventoryTab_Default = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(49, 997),
									ImageRectSize = Vector2.new(16, 18),
								},
								InventoryTab_Selected = {
									Image = "rbxassetid://14874018907",
									ImageRectOffset = Vector2.new(147, 998),
									ImageRectSize = Vector2.new(16, 18),
								},
								Italic_Default = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								Italic_Selected = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Keyword = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								LegacyClientRunContext = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								LegacyServerRunContext = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								Lighting = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								LineForce = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								LineHandleAdornment = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								LinearVelocity = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalFile = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalScript = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalizationService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								LocalizationTable = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Lock = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								LockAll = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								LockCursor = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								LockTool = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								Logpoint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								LogpointDisabled = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								ManagePlugins = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								MarketplaceIcon = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								MarketplaceIcon_Default = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								MarketplaceIcon_Selected = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								MatchCase = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								MatchWholeWord = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Material = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								MaterialService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								MaterialVariant = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								MemoryStoreService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								MeshPart = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								MeshVisibility = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Meshparts = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								MessagingService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Method = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Model = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Modelgroups = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Modified = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								ModifiedPackage = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Module = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								ModuleScript = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								More = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								Motor6D = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								Move = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								Move_P = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Mute = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								NegateOperation = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								NetworkClient = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								NewFile = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								NextResult = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								NoCollision = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								NoCollisionConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								NotFavorited = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 621),
									ImageRectSize = Vector2.new(16, 15),
								},
								NotificationBell = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								NotificationBellNew = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								ObjectBrowser = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								Open = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								OpenHandPointer = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								OpenScriptFunctionFilter = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								Operator = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								OptionsDots = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								OuterCage = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Outline = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								OutlineBoundingBox = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Output = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Package = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								PackageLink = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								PackageLinkAttatchment = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								Packages = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								PanCamera = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								Pants = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Block = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_CornerWedge = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Cylinder = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Sphere = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								Part_Wedge = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								ParticleEmitter = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								Paste = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								PathfindingLink = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								PathfindingModifier = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								PathfindingService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Pause = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Performance = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								PitchShiftSoundEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Place = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlaceCloud = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlaceLocal = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								Placeholder = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								Plane = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlaneConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Play = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								PlayHere = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Player = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								Players = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								PluginGuiService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								PluginRunContext = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								PluginsFolder = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								PointLight = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Pointer = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								PreviousResult = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								PreviousResultOld = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Prismatic = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								PrismaticConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								Properties = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								Property = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								ProximityPrompt = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								PublishService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								QuickOpen = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								QuickOpenActions = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Redo = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								Reference = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								Refresh = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								RefreshOld = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								RegularExpression = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								RemoteEvent = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								RemoteFunction = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								RenderingTest = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Replace = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReplicatedFirst = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReplicatedScriptService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReplicatedStorage = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResetPivot = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResizeDiagonal = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResizeHorizontal = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								ResizeVertical = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Resume = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								ReverbSoundEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rigid = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								RigidConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								RobloxPluginGuiService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								RocketPropulsion = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rod = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								RodConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								RopeConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rotate = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Rotate_P = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Run = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								RunScript = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								Save = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								Scale = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								Scale_P = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScreenGui = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScreenShot = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								Script = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScriptAnalysis = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScriptPerformance = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScriptRecovery = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollbarDown = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollbarTriangle = {
									Image = "rbxassetid://14874017686",
									ImageRectOffset = Vector2.new(980, 38),
									ImageRectSize = Vector2.new(16, 9),
								},
								ScrollbarUp = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								ScrollingFrame = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								Seat = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								Select = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(340, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectAll = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectChildren = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectText = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Select_P = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Selected_Workspace = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectionBox = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								SelectionSphere = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								Separate = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								Server = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								ServerRunContext = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								ServerScriptService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								ServerStorage = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Service = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								Settings = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Shirt = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								ShirtGraphic = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								ShowGrid = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								ShowWelds = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								SkinnedMeshPart = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								Sky = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 340),
									ImageRectSize = Vector2.new(16, 16),
								},
								Smoke = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(357, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								Snap = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(340, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Snippet = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								SocialService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Sound = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								SoundEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								SoundGroup = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								SoundService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								Sparkles = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpawnLocation = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpecialMesh = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								SphereHandleAdornment = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpotLight = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Spring = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								SpringConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								StandalonePluginScripts = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								StartServerAndClient = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterCharacterScripts = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterGui = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterPack = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterPlayer = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 340),
									ImageRectSize = Vector2.new(16, 16),
								},
								StarterPlayerScripts = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 357),
									ImageRectSize = Vector2.new(16, 16),
								},
								StepInto = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(374, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								StepOut = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(357, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								StepOver = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(340, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								Stop = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								Strikethrough_Default = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								Strikethrough_Selected = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								Struct = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								SunRaysEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceAppearance = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceGui = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceLight = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								SurfaceSelection = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								SwimController = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								SwitchWindows = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								TagEditor = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								TaskScheduler = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								Team = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								TeamCreate = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								TeamTest = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								Teams = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								Terrain = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 340),
									ImageRectSize = Vector2.new(16, 16),
								},
								TerrainDetail = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 357),
									ImageRectSize = Vector2.new(16, 16),
								},
								TerrainEditor = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 374),
									ImageRectSize = Vector2.new(16, 16),
								},
								TestService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(391, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextBox = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(374, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextBoxService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(357, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextButton = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(340, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextChannel = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextChatCommand = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextChatService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextLabel = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								TextString = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								Texture = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								Tool = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								Toolbox = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								Torque = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								TorsionSpring = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								TorsionSpringConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Trail = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								Transform = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								Transparency = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								TremoloSoundEffect = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								TrussPart = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								TypeParameter = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 340),
									ImageRectSize = Vector2.new(16, 16),
								},
								UGCValidationService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 357),
									ImageRectSize = Vector2.new(16, 16),
								},
								UI = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 374),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIAspectRatioConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 391),
									ImageRectSize = Vector2.new(16, 16),
								},
								UICorner = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(408, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIGradient = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(391, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIGridLayout = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(374, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIListLayout = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(357, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIOff = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(340, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIOn = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIPadding = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIPageLayout = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIScale = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								UISizeConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								UIStroke = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								UITableLayout = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								UITextSizeConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Underline_Default = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								Underline_Selected = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								Undo = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								UndockPreviewWindow = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								Ungroup = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								UnionOperation = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								Unit = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								Universal = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 340),
									ImageRectSize = Vector2.new(16, 16),
								},
								UniversalConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 357),
									ImageRectSize = Vector2.new(16, 16),
								},
								Unlock = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 374),
									ImageRectSize = Vector2.new(16, 16),
								},
								UnlockCursor = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 391),
									ImageRectSize = Vector2.new(16, 16),
								},
								UpdateAvailable = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 408),
									ImageRectSize = Vector2.new(16, 16),
								},
								UserService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(425, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								Value = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(408, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
								Variable = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(391, 34),
									ImageRectSize = Vector2.new(16, 16),
								},
								VectorForce = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(374, 51),
									ImageRectSize = Vector2.new(16, 16),
								},
								VehicleSeat = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(357, 68),
									ImageRectSize = Vector2.new(16, 16),
								},
								VideoFrame = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(340, 85),
									ImageRectSize = Vector2.new(16, 16),
								},
								VideoRecord = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(323, 102),
									ImageRectSize = Vector2.new(16, 16),
								},
								ViewSelector = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(306, 119),
									ImageRectSize = Vector2.new(16, 16),
								},
								ViewportFrame = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(289, 136),
									ImageRectSize = Vector2.new(16, 16),
								},
								VirtualUser = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(272, 153),
									ImageRectSize = Vector2.new(16, 16),
								},
								VoiceChannel = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(255, 170),
									ImageRectSize = Vector2.new(16, 16),
								},
								VoiceChatService = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(238, 187),
									ImageRectSize = Vector2.new(16, 16),
								},
								Voicechat = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(221, 204),
									ImageRectSize = Vector2.new(16, 16),
								},
								Warning = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(204, 221),
									ImageRectSize = Vector2.new(16, 16),
								},
								Watch = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(187, 238),
									ImageRectSize = Vector2.new(16, 16),
								},
								WedgePart = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(170, 255),
									ImageRectSize = Vector2.new(16, 16),
								},
								Weld = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(153, 272),
									ImageRectSize = Vector2.new(16, 16),
								},
								WeldConstraint = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(136, 289),
									ImageRectSize = Vector2.new(16, 16),
								},
								Wire = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(119, 306),
									ImageRectSize = Vector2.new(16, 16),
								},
								WireframeHandleAdornment = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(102, 323),
									ImageRectSize = Vector2.new(16, 16),
								},
								WireframeRendering = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(85, 340),
									ImageRectSize = Vector2.new(16, 16),
								},
								Workspace = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(68, 357),
									ImageRectSize = Vector2.new(16, 16),
								},
								WorldModel = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(51, 374),
									ImageRectSize = Vector2.new(16, 16),
								},
								WrapLayer = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(34, 391),
									ImageRectSize = Vector2.new(16, 16),
								},
								WrapTarget = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(17, 408),
									ImageRectSize = Vector2.new(16, 16),
								},
								ZoomIn = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(0, 425),
									ImageRectSize = Vector2.new(16, 16),
								},
								ZoomOut = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(442, 0),
									ImageRectSize = Vector2.new(16, 16),
								},
								ZoomTo = {
									Image = "rbxassetid://14874019801",
									ImageRectOffset = Vector2.new(425, 17),
									ImageRectSize = Vector2.new(16, 16),
								},
							},
						},
					},
				},
			},
		},
	},
}